from pydantic import BaseModel, Field
from typing import Optional

class QuestionRequest(BaseModel):
    prompt: str = Field(
        ...,
        description="The question or prompt to send to the LLM agent.",
        example="Explain quantum computing in simple terms."
    )
    system_instruction: Optional[str] = Field(
        default="You are a helpful, professional, and concise assistant.",
        description="Optional system instruction to guide the persona or behavior of the agent."
    )
    temperature: Optional[float] = Field(
        default=1,
        description="Controls the randomness of the model's output. Must be between 0.0 and 2.0.",
        ge=0.0,
        le=2.0
    )

class AnswerResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the LLM agent."
    )
    model_used: str = Field(
        ...,
        description="The model identifier used to generate the response."
    )
    status: str = Field(
        default="success",
        description="Status indicator of the response."
    )
