from pydantic import BaseModel, Field
from typing import Optional

class QuestionRequest(BaseModel):
    prompt: str = Field(
        ...,
        description="The question or prompt to send to the LLM agent.",
        example="Explain quantum computing in simple terms."
    )
    system_instruction: Optional[str] = Field(
        default="You are a helpful, professional, and concise assistant.",
        description="Optional system instruction to guide the persona or behavior of the agent."
    )
    temperature: Optional[float] = Field(
        default=1,
        description="Controls the randomness of the model's output. Must be between 0.0 and 2.0.",
        ge=0.0,
        le=2.0
    )

class AgentHistoryItem(BaseModel):
    agent: str = Field(..., description="Name of the agent or service (e.g. SearchAgent, StoryAgent).")
    role: str = Field(..., description="Role/description of the agent.")
    action: str = Field(..., description="Action taken by the agent.")
    content: str = Field(..., description="Output content or retrieved text from the agent.")
    prompt_tokens: int = Field(default=0, description="Input tokens used by this step.")
    completion_tokens: int = Field(default=0, description="Output tokens generated by this step.")

class TokenUsage(BaseModel):
    prompt_tokens: int = Field(default=0, description="Total input tokens across all steps.")
    completion_tokens: int = Field(default=0, description="Total output tokens generated across all steps.")
    total_tokens: int = Field(default=0, description="Combined total tokens used.")

class AnswerResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the LLM agent."
    )
    model_used: str = Field(
        ...,
        description="The model identifier used to generate the response."
    )
    status: str = Field(
        default="success",
        description="Status indicator of the response."
    )
    token_usage: Optional[TokenUsage] = Field(
        default=None,
        description="Detailed token usage metrics for the execution."
    )
    agent_history: Optional[list[AgentHistoryItem]] = Field(
        default_factory=list,
        description="Chronological chat history of multi-agent execution steps."
    )

class CreateStoryRequest(BaseModel):
    project_key: str = Field(
        ...,
        description="The JIRA project key (e.g. 'FS').",
        example="FS"
    )
    summary: str = Field(
        ...,
        description="The summary or title of the user story.",
        example="Create User Checkout Page"
    )
    description: str = Field(
        ...,
        description="The detailed description of the user story, including acceptance criteria.",
        example="As a customer, I want to..."
    )
    priority: Optional[str] = Field(
        default="Medium",
        description="Business priority (Low, Medium, High, Critical)."
    )
    story_points: Optional[int] = Field(
        default=None,
        description="Optional story points estimation."
    )

class CreateStoryResponse(BaseModel):
    issue_key: str = Field(
        ...,
        description="The key of the created JIRA issue (e.g., 'FS-123')."
    )
    issue_url: str = Field(
        ...,
        description="The URL to view the created JIRA issue."
    )
    status: str = Field(
        default="success",
        description="Status of the operation."
    )

