from pydantic import BaseModel, Field
from typing import Optional

class QuestionRequest(BaseModel):
    prompt: str = Field(
        ...,
        description="The question or prompt to send to the LLM agent.",
        example="Explain quantum computing in simple terms."
    )
    system_instruction: Optional[str] = Field(
        default="You are a helpful, professional, and concise assistant.",
        description="Optional system instruction to guide the persona or behavior of the agent."
    )
    temperature: Optional[float] = Field(
        default=1,
        description="Controls the randomness of the model's output. Must be between 0.0 and 2.0.",
        ge=0.0,
        le=2.0
    )

class AnswerResponse(BaseModel):
    answer: str = Field(
        ...,
        description="The response generated by the LLM agent."
    )
    model_used: str = Field(
        ...,
        description="The model identifier used to generate the response."
    )
    status: str = Field(
        default="success",
        description="Status indicator of the response."
    )

class CreateStoryRequest(BaseModel):
    project_key: str = Field(
        ...,
        description="The JIRA project key (e.g. 'FS').",
        example="FS"
    )
    summary: str = Field(
        ...,
        description="The summary or title of the user story.",
        example="Create User Checkout Page"
    )
    description: str = Field(
        ...,
        description="The detailed description of the user story, including acceptance criteria.",
        example="As a customer, I want to..."
    )
    priority: Optional[str] = Field(
        default="Medium",
        description="Business priority (Low, Medium, High, Critical)."
    )
    story_points: Optional[int] = Field(
        default=None,
        description="Optional story points estimation."
    )

class CreateStoryResponse(BaseModel):
    issue_key: str = Field(
        ...,
        description="The key of the created JIRA issue (e.g., 'FS-123')."
    )
    issue_url: str = Field(
        ...,
        description="The URL to view the created JIRA issue."
    )
    status: str = Field(
        default="success",
        description="Status of the operation."
    )

